### ISSUE TITLE
Xing new hanging

### ISSUE THREAD

**Issue by stevepm** [XingFramework/xing-framework#16]
Hi, I'm going through your gitbook and my terminal is hanging at `xing new crowdfundr`

Here is the output, it will just stop and hang:

xing new crowdfundr
nAdd a Code of Conduct? (Contributor Covenant) [Y/n] n
cp -a /Users/stevenmagelowitz/.rvm/gems/ruby-2.2.0-preview1/gems/xing-framework-1.0.0.pre.beta/default_configuration/base_app crowdfundr => 0
- Copying `database.yml` to `database.yml` succeeded.
- Copying `database.yml.example` to `database.yml.example` succeeded.
- Copying `database.yml.ci` to `database.yml.ci` succeeded.
- Copying `secrets.yml` to `secrets.yml` succeeded.
- Copying `secrets.yml.example` to `secrets.yml.example` succeeded.
- Copying `secrets.yml.ci` to `secrets.yml.ci` succeeded.
- Copying `gitignore` to `.gitignore` succeeded.
- Copying `gitignore` to `.gitignore` succeeded.
- Copying `gitignore` to `.gitignore` succeeded.
- Copying `gitattributes` to `.gitattributes` succeeded.
- Copying `gitattributes` to `.gitattributes` succeeded.
- Copying `gitattributes` to `.gitattributes` succeeded.
- Copying `README.md` to `README.md` succeeded.
- Copying `CONTRIBUTING.md` to `CONTRIBUTING.md` succeeded.
- Copying `CHANGELOG.md` to `CHANGELOG.md` succeeded.
  . /Users/stevenmagelowitz/.rvm/gems/ruby-2.2.0-preview1/gems/xing-framework-1.0.0.pre.beta/bin/xing-rvm-setup-env 2.2.0 && cd crowdfundr && bundle install
  Long running command output:

Using rake 10.5.0
Using caliph 0.3.1
Using calibrate 0.0.1
Using i18n 0.7.0
Using net-ssh 3.0.2
Using chunky_png 1.3.4
Using multi_json 1.11.0
Using sass 3.4.14
Using rb-fsevent 0.9.5
Using ffi 1.9.8
Using tilt 2.0.2
Using valise 1.2.1
Using rack 1.6.4
Using bundler 1.11.2
Using edict 0.0.1
Using net-scp 1.2.1
Using compass-core 1.0.3
Using compass-import-once 1.0.5
Using rb-inotify 0.9.5
Using mattock 0.10.1
Using sshkit 1.8.1
Using compass 1.0.3
Using xing-root 1.0.0.pre.beta
Using capistrano 3.4.0
Using capistrano-passenger 0.2.0
Bundle complete! 5 Gemfile dependencies, 25 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
=> 0
. /Users/stevenmagelowitz/.rvm/gems/ruby-2.2.0-preview1/gems/xing-framework-1.0.0.pre.beta/bin/xing-rvm-setup-env 2.2.0 && cd crowdfundr/frontend && bundle install && npm install
Long running command output:

Using chunky_png 1.3.1
Using multi_json 1.10.1
Using sass 3.4.3
Using rb-fsevent 0.9.4
Using ffi 1.9.3
Using rack 1.5.2
Using bundler 1.11.2
Using compass-core 1.0.1
Using compass-import-once 1.0.5
Using rb-inotify 0.9.5
Using compass 1.0.1
Bundle complete! 3 Gemfile dependencies, 11 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.

**Comment by IdahoEv** [comment]
stevepm, were you able to resolve this?

**Comment by stevepm** [comment]
Yup, it ended up just taking a very long time (approximately 6 minutes).
