### ISSUE TITLE
rake initialize crashes at db.seed

### ISSUE THREAD

**Issue by kke** [XingFramework/xing-framework#22]
Is backend/db/migrate/ empty on purpose?

Running rake initialize crashes at db:seed because there's no tables in the database.

**Comment by IdahoEv** [comment]
rake initialize normally creates and migrates the database for you - in fact that is its primary job.  Can you please paste the output you got, and/or push your code somewhere?  I'd like to dig in and see what's happening.  Which versions of the xing-framework and xing-root gems do you have installed?

**Comment by IdahoEv** [comment]
If you've done a 'xing new' with a recent (i.e 1.0.0-beta.N) release of the xing-framework gem, backend/db/migrate should have three migrations in it.  I just ran a test with 1.0.0-beta.1 and see this:

```
[11:39:38 apps]$ gem install xing-framework --pre
Fetching: xing-framework-1.0.0.pre.beta.1.gem (100%)
Successfully installed xing-framework-1.0.0.pre.beta.1
1 gem installed

[11:39:50 apps]$ xing new foobar
--- LOTS OF OUTPUT HERE ---
** Execute railties:install:migrations
Copied migration 20160211194143_initial.xing.rb from xing
Copied migration 20160211194144_devise_token_auth_add_token_info_to_users.xing.rb from xing
Copied migration 20160211194145_remove_login_from_users.xing.rb from xing
=> 0

[11:41:03 apps]$ cd foobar/

[11:41:14 foobar]$ ls -l backend/db/migrate/
total 24
-rw-r--r--  1 evan  staff  1795 Feb 11 11:41 20160211194143_initial.xing.rb
-rw-r--r--  1 evan  staff   508 Feb 11 11:41 20160211194144_devise_token_auth_add_token_info_to_users.xing.rb
-rw-r--r--  1 evan  staff   170 Feb 11 11:41 20160211194145_remove_login_from_users.xing.rb
```

If you're seeing something different, let me know and we'll help you get to the bottom of it.

**Comment by kke** [comment]
I did it all cleanly on a freshly installed ubuntu vm using rbenv and MRI ruby 2.3.0

1) gem install xing-framework --pre
2) xing new book-app (boy was there a lot of stuff installed there)
3) cd book-app
4) rake initialize
5) I get error about CREATE DATABASE not working due to auth problems, I go into postgres and make myself a superuser and allow passwordless logins.
6) rake initialize

I get this:

```
bundle check || bundle install => 0
bundle exec rake db:create
Long running command output:

=> 0
bundle exec rake db:migrate
Long running command output:

=> 0
bundle exec rake db:seed
Long running command output:

rake aborted!
ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "users" does not exist
LINE 5:                WHERE a.attrelid = '"users"'::regclass
                                          ^
:               SELECT a.attname, format_type(a.atttypid, a.atttypmod),
                     pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
                FROM pg_attribute a LEFT JOIN pg_attrdef d
                  ON a.attrelid = d.adrelid AND a.attnum = d.adnum
               WHERE a.attrelid = '"users"'::regclass
                 AND a.attnum > 0 AND NOT a.attisdropped
               ORDER BY a.attnum
/home/ubuntu/Projects/book-app/backend/db/seeds.rb:8:in `<top (required)>'
PG::UndefinedTable: ERROR:  relation "users" does not exist
LINE 5:                WHERE a.attrelid = '"users"'::regclass
                                          ^
/home/ubuntu/Projects/book-app/backend/db/seeds.rb:8:in `<top (required)>'
Tasks: TOP => db:seed
(See full trace by running task with --trace)
=> 1
rake aborted!
Command 'bundle exec rake db:seed' failed with exit status 1:

```

Then, not being new to rails, I go to backend and see what the migrations look like:

```
$ pwd
/home/ubuntu/Projects/ubuntu/book-app/backend 
$ ls db/migrate -al
total 8
drwxrwxr-x 2 ubuntu ubuntu 4096 Feb 11 19:12 .
drwxrwxr-x 4 ubuntu ubuntu 4096 Feb 11 20:28 ..
-rw-r--r-- 1 ubuntu ubuntu    0 Feb 11 19:12 .gitkeep
```

Wondering about this, I go to [github/XingFramework/......default_configuration/base_app/backend/db/migrate](https://github.com/XingFramework/xing-framework/tree/master/default_configuration/base_app/backend/db/migrate) and notice it's empty there too, so decided to create an issue and here we are.

Postgres shows this:

```
=# \dt;
             List of relations
 Schema |       Name        | Type  | Owner
--------+-------------------+-------+-------
 public | schema_migrations | table | ubuntu
(1 row)
#= select * from schema_migrations;
 version
---------
(0 rows)

```

**Comment by IdahoEv** [comment]
Thanks. That directory (in base_app) only exists to make sure an empty db/migrate gets created.  The actual db migrations live here, in the xing-backend gem:  https://github.com/XingFramework/xing-backend/tree/master/db/migrate.

The rake task that creates those should have been called by rake new.  But I'm wondering if the xing-backend gem didn't install properly for you.  Can you cd to the backend/ subdirectory and paste me the output of `bundle show xing-backend`?

The other thing I'd love to see is the last ~20 lines or so of your output from `xing new`, but you'd have to generate another empty app.  Other things that may help me track this down: are you using a ruby version manager (rbenv, rvm, chruby), etc, and if so which one?

**Comment by kke** [comment]
/home/ubuntu/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/xing-backend-1.0.0.pre.beta

Using rbenv and ruby 2.3.0.

I remember now that I did get some bundle errors for not having libpq-dev, but I tracked down allthe Gemfile's and ran bundle install in those directories.

Maybe I need to try a fresh one. See you in few hours when it finishes :)

**Comment by IdahoEv** [comment]
in the backend directory, if you run `rake railties:install:migrations` does it create the migration files?

**Comment by kke** [comment]
Yeah, that created the migrations. Let's see what happens with rake:initialize now.

No luck there:

```
$  rake initialize
which tmux => 0
Using Xing::Managers::TmuxPane
bundle check || bundle install => 0
bundle exec rake db:create
Long running command output:

book-app_dev already exists
book-app_test already exists
=> 0
bundle exec rake db:migrate
Long running command output:

rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::UndefinedFile: ERROR:  could not open extension control file "/usr/share/postgresql/9.3/extension/hstore.control": No such file or directory
: CREATE EXTENSION IF NOT EXISTS "hstore"/home/ubuntu/Projects/book-app/backend/db/migrate/20160211201623_initial.xing.rb:7:in `up'
ActiveRecord::StatementInvalid: PG::UndefinedFile: ERROR:  could not open extension control file "/usr/share/postgresql/9.3/extension/hstore.control": No such file or directory
: CREATE EXTENSION IF NOT EXISTS "hstore"
/home/ubuntu/Projects/book-app/backend/db/migrate/20160211201623_initial.xing.rb:7:in `up'
PG::UndefinedFile: ERROR:  could not open extension control file "/usr/share/postgresql/9.3/extension/hstore.control": No such file or directory
/home/ubuntu/Projects/book-app/backend/db/migrate/20160211201623_initial.xing.rb:7:in `up'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
== 20160211201623 Initial: migrating ==========================================
-- enable_extension("plpgsql")
   -> 0.0031s
-- enable_extension("hstore")
=> 1
rake aborted!
Command 'bundle exec rake db:migrate' failed with exit status 1:
stdout:
== 20160211201623 Initial: migrating ==========================================
-- enable_extension("plpgsql")
   -> 0.0031s
-- enable_extension("hstore")
stderr:
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::UndefinedFile: ERROR:  could not open extension control file "/usr/share/postgresql/9.3/extension/hstore.control": No such file or directory
: CREATE EXTENSION IF NOT EXISTS "hstore"/home/ubuntu/Projects/book-app/backend/db/migrate/20160211201623_initial.xing.rb:7:in `up'
ActiveRecord::StatementInvalid: PG::UndefinedFile: ERROR:  could not open extension control file "/usr/share/postgresql/9.3/extension/hstore.control": No such file or directory
: CREATE EXTENSION IF NOT EXISTS "hstore"
/home/ubuntu/Projects/book-app/backend/db/migrate/20160211201623_initial.xing.rb:7:in `up'
PG::UndefinedFile: ERROR:  could not open extension control file "/usr/share/postgresql/9.3/extension/hstore.control": No such file or directory
/home/ubuntu/Projects/book-app/backend/db/migrate/20160211201623_initial.xing.rb:7:in `up'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
---
Tasks: TOP => initialize => initialize:all => backend:initialize => backend:db_seed => backend:db_migrate
(See full trace by running task with --trace)

```

**Comment by kke** [comment]
I'll start from the top.

**Comment by IdahoEv** [comment]
Ok, so I think likely that's what happened.  The compile error on plpgsql caused xing new to exit before it was finished, so you never got the migration files templated.  It's _possible_ that other important parts of `xing new` didn't complete, either.

If you've gotten the pg compile straightened out, then yes go ahead and try a new run and see if it works for you.  The second run should go much faster because all the gems are already installed.

Let me know how it goes.

**Comment by nyarly** [comment]
@kke - it looks like you may not have the postgres-contrib package installed for Ubuntu. By default, we use hstore in a number of tables, and that's provided from that package. Can you try something like:

```
sudo apt-get install postgresql-contrib
```

**Comment by kke** [comment]
That should probably be in the "get started" prerequisites

**Comment by IdahoEv** [comment]
I'll add it now.

**Comment by kke** [comment]
Ok now it went through fine.

Now running rake develop wondering where it'll take me.

I never imagined building a rails-api + angular app would be that complicated, but there's like 300mb of stuff in my app dir already.

**Comment by kke** [comment]
Looks like it requires node too, not just npm.

**Comment by IdahoEv** [comment]
npm requires node, so that's a given.

**Comment by IdahoEv** [comment]
Glad to hear it's working! If you run into anything else, let us know and we'll do our  best to help.  (And yes, between two big frameworks written in two different languages, there are a _ton_ of modules that get installed.)

**Comment by kke** [comment]
I had to apt-get installed npm, still I had to run apt-get install node to get the rake develop running.

**Comment by IdahoEv** [comment]
Hrm, ok. I'm a mac user, so I'm not too familiar with apt.  I'm surprised npm will install without node.

**Comment by kke** [comment]
I don't think I'm going to touch it again. 

I thought it was targeted to rails people who just want to get some angular on but looks like it's not for me. Too much going on that I don't have a clue about. 

All I wanted was to pull a rails-api project from github that had `public/angular.html` that gets a hello world from the API but looks like it's not as simple as I anticipated.

Xing might be the bees knees to some, but for me, a long time Rails developer that fell off the hipster wagon and didn't keep up with the JS SPA stuff, there's just too much strange stuff going on that I don't feel comfortable with. Need to start with something simpler. And once (if ever) I know that stuff, I don't think I'll need Xing for anything.

**Comment by IdahoEv** [comment]
Understood, thanks for trying it out.  SPA development is definitely a huge ball of wax - IMO as big as Rails.  Xing tries to simplify some of it by giving you a cleaner angular syntax and predefining & tooling a transport layer, but in the end it's still Angular.JS development -- no way around that.

**Comment by hannahhoward** [comment]
Hi @kke, thanks for the feedback. We get it. Really. Our goal is really to make things easy as rails, but it's a long path to that point. The truth is we've don a ton of work to make things easier, but an API + SPA really is a totally different platform than Rails was originally designed for. We've been try to clear as many paths as we can, but there are many paths still to clear. Please do keep in mind you're comparing to Rails in its modern form -- which developed over many years. In contrast, Xing is a 1.0 product. Also, the truth is the JS world needs to standardize and improve some of it's tooling before this can really be as simple as Rails.
