### ISSUE TITLE
prerequisites link... file not found

### ISSUE THREAD

**Issue by neuronsong** [XingFramework/xing-framework#25]
https://xingframework.gitbooks.io/the-xing-framework/content/introduction/prerequisites.md

**Comment by neuronsong** [comment]
I failed to mention the link is broken from this page:
https://xingframework.gitbooks.io/the-xing-framework/content/introduction/super_fast_start.html

**Comment by IdahoEv** [comment]
Thanks for the note! I've fixed the broken link this morning.

Gitbook is terrible for maintaining links ... we're looking for alternate solutions.
